FROM rust:1.79.0-bookworm as builders
WORKDIR /app

COPY Cargo.toml Cargo.lock /app/
RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
RUN cargo build --release

COPY . /app
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /tmp/target/release/axum-lambda-sample /app/axum-lambda-sample
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.3 /lambda-adapter /opt/extensions/lambda-adapter
CMD ["./axum-lambda-sample"]
